accounts/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse_lazy

from .views import (
    NotificationsListView,
    PortfolioListView,
    TransactionsListView,
    UserDetailView,
    UserProfileCreateView,
    UserProfileDetailView,
    UsersGroupListView,
    UsersListView,
    UserUpdateView,
    login,
)

urlpatterns = patterns('',
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('home')}, name='logout'),
    url(r'^create/$', UserProfileCreateView.as_view(), name='create'),
    url(r'^rank/$', UsersListView.as_view(), name='rank'),
    url(r'^groups/(?P<pk>[0-9]+)(/)*$', UsersGroupListView.as_view(), name='groups'),
    url(r'^(?P<pk>[0-9]+)/$', UserDetailView.as_view(), name='user'),  # '/accounts/<pk>/'
    url(r'^(?P<pk>[0-9]+)/zawartoscportfela/$', PortfolioListView.as_view(), name='user_portfolio'),
    url(r'^(?P<pk>[0-9]+)/powiadomieniaowynikach/$', NotificationsListView.as_view(), name='user_notifications'),
    url(r'^(?P<pk>[0-9]+)/historiatransakcji/$', TransactionsListView.as_view(), name='user_transactions'),
    url(r'^user_settings/$', UserUpdateView.as_view(), name='user_settings'),
    url(r'^user_profile/$', UserProfileDetailView.as_view(),
        name='user_profile'),
)

cms/urls.py
from django.conf.urls import url

from .views import IndexView, PageDetailView

urlpatterns = [
    # url(r'^$', IndexView.as_view(), name='index_news'),
    url(r'^(?P<slug>[\w-]+)$', PageDetailView.as_view(), name='page'),
]

politikon/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns

from .api import ContactAPIView
from .views import HomeView, ContactView, acme_challenge, change_language

from events.urls import api_urls as event_api

from django.contrib import admin
admin.autodiscover()


api_urls = [
    url(r'contact/', ContactAPIView.as_view(), name='api-contact'),
    # Responsible for betting
    url(r'events/', include(event_api, namespace='api-events')),
    url(r'^auth/', include('djoser.urls.authtoken'))
]

urlpatterns = patterns(
    '',
    url(r'^change_language/(?P<lang>(pl|en|lt))$', change_language, name='change_language'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^api/', include(api_urls)),
    url(r'^.well-known/acme-challenge/(?P<acme>\w+)$', acme_challenge, name='acme_challenge'),
    url(r'^event/(?P<event_id>\d+)/transaction/create/$', 'events.views.create_transaction',
        name="create_transaction"),
    url(r'^event/(?P<event_id>\d+)/resolve/$', 'events.views.resolve_event',
        name="resolve_event"),
)

urlpatterns += i18n_patterns(
    '',
    # Admin url patterns
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    # User authentication url patternsapi
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # Application url patterns
    url(r'^', include('events.urls', namespace='events')),

    # CMS pages
    url(r'^pages/', include('cms.urls', namespace='cms')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^contact/$', ContactView.as_view(), name='contact')
)

if settings.SERVE_STATIC_FILES:
    urlpatterns += patterns(
        '',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.admin import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import UserProfile


class UserCreationForm(forms.ModelForm):
    """
    Form for creating new users. Includes all the required fields
    and repeated password. Used on admin site.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = UserProfile
        fields = '__all__'

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords didn't match.")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserSelfRegisterForm(forms.ModelForm):
    """A form for creating new users from popup on website."""
    checkemail = forms.EmailField(label='Repeat email')
    regulamin = forms.BooleanField(label='Acknowledge')

    class Meta:
        model = UserProfile
        fields = ['password', 'username', 'email', 'checkemail', 'regulamin']

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserSelfRegisterForm, self).save(commit=False)
        user.is_active = False
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField(
        label=("Password"),
        help_text=("Raw passwords are not stored, so there is no way to see "
                   "this user's password, but you can change the password "
                   "using <a href=\"password/\">this form</a>."))

    class Meta:
        model = User
        fields = '__all__'

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserProfileAvatarForm(forms.ModelForm):
    """
    A form for updating user avatar.
    """

    class Meta:
        model = UserProfile
        fields = ['avatar']


class UserProfileForm(forms.ModelForm):
    """
    A form for updating user data, part 1. Includes name, website and user
    description.
    """

    class Meta:
        model = UserProfile
        fields = ['name', 'web_site', 'description']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['web_site'].required = False
        self.fields['description'].required = False


class UserProfileEmailForm(forms.ModelForm):
    """
    A form for updating user data, part 2. Includes passwords and emails
    fields.
    """
    email = forms.CharField(label='Twój adres e-mail', widget=forms.EmailInput, required=False)
    checkemail = forms.CharField(label='wpisz ponownie adres e-mail', widget=forms.EmailInput,
                                 required=False)

    class Meta:
        model = UserProfile
        fields = []

    def clean(self):
        super(UserProfileEmailForm, self).clean()
        if self.cleaned_data.get('email') != self.cleaned_data.get('checkemail'):
            self._errors['checkemail'] = 'Email addresses do not match.'
            # raise ValidationError('Email addresses do not match.')
        return self.cleaned_data


class TeamAccessKeyForm(forms.Form):
    value = forms.CharField(label='Klucz Grupy', max_length=60)

accounts/views.py
# -*- coding: utf-8 -*-
from collections import namedtuple
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, CreateView
from django.utils.translation import ugettext as _

from .exceptions import InvalidAccessKey, TeamJoiningError
from .forms import (
    UserProfileAvatarForm, UserProfileForm, UserProfileEmailForm,
    UserSelfRegisterForm, TeamAccessKeyForm
)
from .models import UserProfile, Team, TeamAccessKey

from events.models import Bet, TeamResult, Transaction
from politikon.decorators import class_view_decorator
from politikon.forms import MultiFormsView

# these bellow imports are for login function
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import resolve_url
from django.utils.http import is_safe_url
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse


PORTFOLIO_ON_PAGE = 12
NOTIFICATIONS_ON_PAGE = 10
TRANSACTIONS_ON_PAGE = 10


@class_view_decorator(login_required)
class UserUpdateView(MultiFormsView):
    """
    User settings
    """
    # TODO: nie do końca o to chodziło, ale jest lepiej
    template_name = 'accounts/user_settings.html'
    form_classes = {
        'main': UserProfileForm,
        'email': UserProfileEmailForm,
        'avatar': UserProfileAvatarForm,
        'group': TeamAccessKeyForm
    }
    model = UserProfile
    success_url = reverse_lazy('accounts:user_settings')

    def get_object(self):
        return get_object_or_404(UserProfile, pk=self.request.session['_auth_user_id'])

    def main_form_valid(self, form):
        user = self.get_object()
        user.name = self.request.POST.get('name')
        user.web_site = self.request.POST.get('web_site')
        user.description = self.request.POST.get('description')
        if self.request.FILES.get('avatar'):
            user.avatar = self.request.FILES.get('avatar')
        user.save()
        return redirect(self.success_url)

    def email_form_valid(self, form):
        user = self.get_object()
        user.email = self.request.POST.get('email')
        if self.request.FILES.get('avatar'):
            user.avatar = self.request.FILES.get('avatar')
        user.save()
        return redirect(self.success_url)

    def group_form_valid(self, form):
        """
        view which adds user to a group
        """
        key_value = form.data.get('value')
        try:
            access_key = TeamAccessKey.objects.get(value=key_value)
            user = self.get_object()
            user.join_team(access_key.team)
        except TeamAccessKey.DoesNotExist:
            raise InvalidAccessKey(u"Podany klucz dostępu jest nieprawidłowy")
        return redirect(self.success_url)

    def post(self, request, *args, **kwargs):
        try:
            return super(UserUpdateView, self).post(request, *args, **kwargs)
        except TeamJoiningError as e:
            return render(
                    self.request,
                    'accounts/user_settings.html',
                    context={'error': e.message})


@class_view_decorator(login_required)
class UserProfileDetailView(DetailView):
    """
    Logged user profile detail (user.id from session)
    """
    model = UserProfile
    template_name = 'accounts/userprofile_detail.html'

    def get_object(self, **kwargs):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserProfileDetailView, self).\
            get_context_data(*args, **kwargs)
        user = self.get_object()
        portfolio_page = Paginator(user.bets.get_in_progress(), PORTFOLIO_ON_PAGE).page(1)
        notifications_page = Paginator(Bet.objects.get_finished(user), NOTIFICATIONS_ON_PAGE).page(1)
        transactions_page = Paginator(Transaction.objects.get_user_transactions_after_reset(user),
                                           TRANSACTIONS_ON_PAGE).page(1)
        context.update(UserProfile.objects.get_user_positions(user))
        context.update({
            'user_pk': user.pk,
            'json_data': json.dumps(user.get_reputation_history()),
            'portfolio_list': portfolio_page.object_list,
            'portfolio_page': portfolio_page,
            'notifications_list': notifications_page.object_list,
            'notifications_page': notifications_page,
            'transactions_list': transactions_page.object_list,
            'transactions_page': transactions_page,
        })
        return context


class UserDetailView(DetailView):
    """
    User profile detail. Any user can see this page (user.id from url)
    """
    model = UserProfile
    template_name = 'accounts/user_detail.html'

    def get_object(self, **kwargs):
        """
        User detail
        :return:
        :rtype: QuerySet
        """
        user_detail = super(UserDetailView, self).get_object(**kwargs)
        return user_detail

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(*args, **kwargs)
        user = self.get_object()
        portfolio_page = Paginator(user.bets.get_in_progress(), PORTFOLIO_ON_PAGE).page(1)
        notifications_page = Paginator(Bet.objects.get_finished(user), NOTIFICATIONS_ON_PAGE).page(1)
        transactions_page = Paginator(Transaction.objects.get_user_transactions_after_reset(user),
                                           TRANSACTIONS_ON_PAGE).page(1)
        context.update(UserProfile.objects.get_user_positions(user))
        context.update({
            'user_pk': user.pk,
            'json_data': json.dumps(user.get_reputation_history()),
            'portfolio_list': portfolio_page.object_list,
            'portfolio_page': portfolio_page,
            'notifications_list': notifications_page.object_list,
            'notifications_page': notifications_page,
            'transactions_list': transactions_page.object_list,
            'transactions_page': transactions_page,
        })
        return context


class PortfolioListView(ListView):
    """
    Portfolio list in userprofile
    """
    template_name = 'accounts/portfolio.html'
    paginate_by = PORTFOLIO_ON_PAGE
    context_object_name = 'portfolio_list'

    def get_object(self):
        return UserProfile.objects.get(pk=self.kwargs['pk'])

    def get_queryset(self):
        user = self.get_object()
        return user.bets.get_in_progress()

    def get_context_data(self, *args, **kwargs):
        context = super(PortfolioListView, self).get_context_data(*args, **kwargs)
        user = self.get_object()
        context.update({
            'portfolio_page': context['page_obj'],
            'object': user,
            'user_pk': user.pk,
            'json_data': json.dumps(user.get_reputation_history()),
        })
        return context


class NotificationsListView(ListView):
    """
    Notifications list in userprofile
    """
    template_name = 'accounts/notifications.html'
    paginate_by = NOTIFICATIONS_ON_PAGE
    context_object_name = 'notifications_list'

    def get_object(self):
        return UserProfile.objects.get(pk=self.kwargs['pk'])

    def get_queryset(self):
        user = self.get_object()
        return Bet.objects.get_finished(user)

    def get_context_data(self, *args, **kwargs):
        context = super(NotificationsListView, self).get_context_data(*args, **kwargs)
        user = self.get_object()
        context.update({
            'notifications_page': context['page_obj'],
            'object': user,
            'user_pk': user.pk,
            'json_data': json.dumps(user.get_reputation_history()),
        })
        return context


class TransactionsListView(ListView):
    """
    Transactions list in userprofile
    """
    template_name = 'accounts/transactions.html'
    paginate_by = TRANSACTIONS_ON_PAGE
    context_object_name = 'transactions_list'

    def get_object(self):
        return UserProfile.objects.get(pk=self.kwargs['pk'])

    def get_queryset(self):
        user = self.get_object()
        return Transaction.objects.get_user_transactions_after_reset(user)

    def get_context_data(self, *args, **kwargs):
        context = super(TransactionsListView, self).get_context_data(*args, **kwargs)
        user = self.get_object()
        context.update({
            'transactions_page': context['page_obj'],
            'object': user,
            'user_pk': user.pk,
            'json_data': json.dumps(user.get_reputation_history()),
        })
        return context


class UsersListView(ListView):
    """
    Users list in rank
    """
    template_name = 'accounts/rank.html'

    def get_queryset(self):
        """
        Users list
        :return:
        :rtype: QuerySet
        """
        return UserProfile.objects.get_best_overall()

    def get_context_data(self, *args, **kwargs):
        context = super(UsersListView, self).get_context_data(*args, **kwargs)
        user = self.request.user
        if user.is_authenticated():
            context.update(UserProfile.objects.get_user_positions(user))
            context['json_data'] = json.dumps(user.get_reputation_history())
        TeamRank = namedtuple('TeamRank', 'team, elo')
        team_results = TeamResult.objects.get_ranking_view()
        other_teams = Team.objects.exclude(
            id__in=team_results.values_list('team_id', flat=True)
        )
        team_leaders = [
            TeamRank(result.team, result.elo) for result in team_results
        ] + [TeamRank(team, None) for team in other_teams]
        context.update({
            'best_weekly': UserProfile.objects.get_best_weekly(),

templates/accounts/notifications.html
{% load user %}

{% block userinfo %}
<section id="userinfo" class="hotbets prefooter-margin">
    {% user_notifications %}
</section>
{% endblock %}

templates/accounts/portfolio.html
{% load user %}

{% block userinfo %}
<section id="userinfo" class="hotbets prefooter-margin">
    {% user_portfolio %}
</section>
{% endblock %}

templates/accounts/transactions.html
{% load user %}

{% block userinfo %}
<section id="userinfo" class="hotbets prefooter-margin">
    {% user_transactions %}
</section>
{% endblock %}

templates/accounts/user_home.html
{% load format %}
<div class="userrank{% if user.is_vip %} uservip{% endif %}">
    <a href="{{ user.get_absolute_url }}">
        <div class="image" style="background-image: url({{ user.get_avatar_url }});"></div>
        <div class="wolnereputy"><span class="astable">{{ reputation_change|formatted:is_formatted }} %</span></div>
        <div class="username">{{ user.name }}</div>
    </a>
</div>

templates/accounts/user_notifications.html
{% load display format static i18n %}
<div id="notifications-list">
    {% for bet in objects_list %}
    <div class="notifications-item notinwallet betresult{% if bet.is_new_resolved %} new{% endif %}">
        <a data-bet_id="{{ bet.id }}" href="{{ bet.event.get_relative_url }}">
            {% if bet.event.small_image %}
            <div class="image" style="background-image: url({{ bet.event.small_image.url }});"></div>
            {% else %}
            <div class="image" style="background-image: url({% static 'img/bet-plain.jpg' %});"></div>
            {% endif %}
            {% render_bet_status bet %}
            <div class="status-explanation">
                <span>{% trans "explanation of the result:" %}</span>
                {{ bet.event.outcome_reason|safe }}
            </div>
            <div class="status-change">
                {% trans "profit" %}/{% trans "loss" %}:
                <div class="{% if bet.is_won %}changeYES{% else %}changeNO{% endif %}">{{ bet.get_wallet_change|formatted:"True" }}</div>
                <p><span class="invested">{{ bet.get_invested|formatted }}</span> <span class="won">{{ bet.get_won|formatted }}</span></p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% if page_obj.has_next %}
<a class="notifications-loadmore loadmore" href="{% url 'accounts:user_notifications' pk=user_pk %}?page={{ page_obj.next_page_number }}">
    <div class="btn astable">{% trans "show more results" %}</div>
</a>
{% endif %}

templates/accounts/user_portfolio.html
{% load format i18n %}
<div id="portfolio-list">
    {% for bet in objects_list %}
    <div class="betinwallet betresult new portfolio-item">
        <a href="{{ bet.event.get_relative_url }}">
            <div class="image" style="background-image: url({{ bet.event.small_image.url }}); width: 136px; background-size: cover; height: 100px; display: block; float: left; margin-right: 3.75%; margin-top: 5px;"></div>
            <div class="status">
                <h3 class="skroc">{{ bet.event }}</h3>
                <p title="Wartość zaokrąglona"><span class="betdetails">{% trans "Bet" %}:</span> <span class="{% if bet.outcome %}changeYES{% else %}changeNO{% endif %}">{% if bet.outcome %}{% trans "YES" %}{% else %}{% trans "NO" %}{% endif %}</span> {{ bet.has }} x <span class="reputy-small"></span>{{ bet.bought_avg_price|formatted }} <span class="why">({% trans "current price" %}: {{ bet.current_event_price }})</span></p>
                <p class="detailed-status"><span class="invested">{{ bet.get_invested|formatted }}</span> <span class="maywin">{{ bet.get_won|formatted }}</span> <span class="inwallet">{{ bet.get_wallet_change|formatted:"True" }}</span></p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% if page_obj.has_next %}
<a class="portfolio-loadmore loadmore" href="{% url 'accounts:user_portfolio' pk=user_pk %}?page={{ page_obj.next_page_number }}">
    <div class="btn astable">{% trans "show more events" %}</div>
</a>
{% endif %}

templates/accounts/user_settings.html
{% extends "base.html" %}

{% load display static i18n %}

{% block js_scripts %}
<script type="text/javascript" src="{% static 'js/intro/scenario-settings.js' %}"></script>
{% if error %}<script type="text/javascript">alert('{{ error }}')</script>{% endif %}
{% endblock %}

{% block content %}

<section id="settings-profile" class="body-margin">
    <form action="{% url 'accounts:user_settings' %}" method="post" enctype="multipart/form-data" id="avatar">
        {% csrf_token %}
        <div class="upload-wrapper" data-current="{{ forms.avatar.instance.avatar }}" data-current-url="{% if forms.avatar.instance.avatar %}{{ forms.avatar.instance.avatar.url }}{% else %}{{ user.get_avatar_url }}{% endif %}">
            <a href="#">
                <figure class="profile-avatar lewa">
                    <figcaption>
                        <span>{% trans "change avatar" %}</span>
                    </figcaption>
                    <div class="image preview" style="background-image: url({{ user.get_avatar_url }});"></div>
                </figure>
            </a>
            <div class="hidden">
                {{ forms.avatar }}
            </div>
        </div>
    </form>
    <div class="current-settings lewa">
        <div class="astable">
            <h2>{% if user.name %}{{ user.name }}{% else %}-{% endif %}</h2>
            <p><span class="what">{% trans "Player" %}:</span> <span class="value">{{ user.username }}</span></p>
            <p><span class="what">{% trans "Joined game" %}:</span> <span class="value">{{ user.created_date }}</span></p>
        </div>
        <div class="astable">
            <p><span class="what">{% trans "E-mail address" %}:</span> <span class="value">{% if user.email %}<a href="emailto:{{ user.email }}">{{ user.email }}</a>{% else %}-{% endif %}</span></p>
            <p><span class="what">{% trans "Connected accounts" %}:</span> <span class="value">
                {% if user.twitter_user %}
                <a href="{{ user.get_twitter_url }}"><span class="att-tt">{{ user.twitter_user }}</span></a>
                {% endif %}
                {% if user.facebook_user %}
                <a href="{{ user.get_facebook_url }}"><span class="att-fb">{{ user.facebook_user }}</span></a>
                {% endif %}
                {% if not user.twitter_user and not user.facebook_user %}-{% endif %}
            </span></p>
        </div>
    </div>
</section>

<section id="userinfo" class="hotbets">
    <ul class="tabs lewa">
        <li class="active"><a href="#profil">{% trans "Your profile" %}</a></li>
        <li><a href="#haslo">E-mail</a></li>
        <li><a href="#group">{% trans "Group" %}</a></li>
    </ul>
    <div class="clr"></div>
    <div class="zakladki-content">
        <article id="profil" class="active">
            <form data-parsley-validate action="{% url 'accounts:user_settings' %}" method="post" enctype="multipart/form-data" class="settings-form" id="profil">
                {% csrf_token %}
                <div class="lewa">
                    <span>{% trans "Name as presented" %}:</span>
                    <input name="name" type="text" class="jednalinia" id="{{ forms.main.name.auto_id }}" value="{{ user.name }}" data-parsley-minlength="3" data-parsley-trigger="focusout" required />
                    <span>{% trans "Player's description" %}:</span>
                    <textarea name="description" class="wielelinii" id="{{ forms.main.description.auto_id }}" data-parsley-minlength="10" data-parsley-trigger="focusout">{{ user.description }}</textarea>
                </div>
                <div class="prawa">
                    <span>{% trans "Your website" %}:</span>
                    <input name="web_site" type="url" class="jednalinia" id="{{ forms.main.web_site.auto_id }}" value="{{ user.web_site }}" data-parsley-type="url" data-parsley-trigger="focusout">
                    <span>{% trans "Connected accounts" %}:</span>
                    {% if user.twitter_user %}
                    <div class="social-connect connection"><div class="connect-tt"></div>{{ user.twitter_user }}</div>
                    {% endif %}
                    {% if user.facebook_user %}
                    <div class="social-connect connection"><div class="connect-fb"></div>{{ user.facebook_user }}</div>
                    {% endif %}
                </div>
            </form>
        </article>

        <article id="haslo">
            <form data-parsley-validate action="{% url 'accounts:user_settings' %}" method="post" enctype="multipart/form-data" class="settings-form" id="haslo">
                {% csrf_token %}
                <div class="lewa">
                    <span>{% trans "Change e-mail address" %}:</span>
                    <input name="email" type="email" class="jednalinia" id="{{ forms.email.email.auto_id }}" value="{{ user.email }}" placeholder="{{ forms.email.email.label }}" data-parsley-trigger="focusout" required>
                    <input name="checkemail" type="email" class="jednalinia" id="{{ forms.email.checkemail.auto_id }}" placeholder="{{ forms.email.checkemail.label }}" data-parsley-equalto="#newemail" data-parsley-trigger="focusout" required>
                </div>
                {% comment %}
                <div class="prawa">
                    <span>Zmień swoje hasło:</span>
                    <input name="oldpass" type="password" class="jednalinia" id="{{ forms.email.old_password.auto_id }}" placeholder="{{ forms.email.old_password.label }}" data-parsley-minlength="4" data-parsley-trigger="focusout">
                    <input name="newpass" type="password" class="jednalinia" id="{{ forms.email.password1.auto_id }}" placeholder="{{ forms.email.password1.label }}" data-parsley-minlength="4" data-parsley-trigger="focusout">
                    <input name="checkpass" type="password" class="jednalinia" id="{{ forms.email.password2.auto_id }}" placeholder="{{ forms.email.password2.label }}" data-parsley-minlength="4" data-parsley-equalto="#newpass" data-parsley-trigger="focusout" required>
                </div>
                {% endcomment %}
            </form>
        </article>

        <article id="group">
            {% if user.team %}
                <div class="lewa">
                    <a href={% url 'accounts:groups' user.team.pk %}>
                        {{ user.team.name }}
                    </a>
                </div>
            {% else %}
                <form action="{% url 'accounts:user_settings' %}" method="post" class="settings-form" id="group">
                    {% csrf_token %}
                    <div class="lewa">
                        <span>{% trans "Enter group access key" %}:</span>
                        <input name="value" type="text" class="jednalinia" required>
                    </div>
                </form>
            {% endif %}
        </article>
    </div>
</section>

<section id="settings-submit" class="prefooter-margin">
    {% for message in messages %}
    <div{% if message.1 %} class="error"{% endif %}>{{ message.0 }}</div>
    {% endfor %}
    <a href="#" id="loadmore" class="loadmore"><div class="btn astable">{% trans "Save changes" %}</div></a>
</section>

{% endblock %}

templates/accounts/user_transactions.html
{% load format i18n %}
<div id="transactions-list">
    {% for transaction in objects_list %}
    <div class="history-event transactions-item">
        <span class="skroc lewa {# changeYES changeNO #}">{{ transaction.event.title }}</span>
        <div class="prawa">
            <span class="history-action">{{ transaction.get_type_display|upper }}</span>
            <span class="reputy-change {% if transaction.price > 0 %}changeYES{% else %}changeNO{% endif %}"><span class="reputy-small"></span>{{ transaction.price|formatted:"True" }}</span>
            {# <span class="wallet-change {% if transaction.total_wallet >= 0 %}changeYES{% else %}changeNO{% endif %}"><span class="reputy-small"></span>{{ transaction.total_wallet|formatted:"True" }}</span>#}
            <span class="event-date">{{ transaction.date }}</span>
        </div>
    </div>
    {% endfor %}
</div>
{% if page_obj.has_next %}
<a class="transactions-loadmore loadmore" href="{% url 'accounts:user_transactions' pk=user_pk %}?page={{ page_obj.next_page_number }}">
    <div class="btn astable">{% trans "show more predictions" %}</div>
</a>
{% endif %}