accounts/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse_lazy

from .views import (
    NotificationsListView,
    PortfolioListView,
    TransactionsListView,
    UserDetailView,
    UserProfileCreateView,
    UserProfileDetailView,
    UsersGroupListView,
    UsersListView,
    UserUpdateView,
    login,
)

urlpatterns = patterns('',
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('home')}, name='logout'),
    url(r'^create/$', UserProfileCreateView.as_view(), name='create'),
    url(r'^rank/$', UsersListView.as_view(), name='rank'),
    url(r'^groups/(?P<pk>[0-9]+)(/)*$', UsersGroupListView.as_view(), name='groups'),
    url(r'^(?P<pk>[0-9]+)/$', UserDetailView.as_view(), name='user'),  # '/accounts/<pk>/'
    url(r'^(?P<pk>[0-9]+)/zawartoscportfela/$', PortfolioListView.as_view(), name='user_portfolio'),
    url(r'^(?P<pk>[0-9]+)/powiadomieniaowynikach/$', NotificationsListView.as_view(), name='user_notifications'),
    url(r'^(?P<pk>[0-9]+)/historiatransakcji/$', TransactionsListView.as_view(), name='user_transactions'),
    url(r'^user_settings/$', UserUpdateView.as_view(), name='user_settings'),
    url(r'^user_profile/$', UserProfileDetailView.as_view(),
        name='user_profile'),
)

cms/urls.py
from django.conf.urls import url

from .views import IndexView, PageDetailView

urlpatterns = [
    # url(r'^$', IndexView.as_view(), name='index_news'),
    url(r'^(?P<slug>[\w-]+)$', PageDetailView.as_view(), name='page'),
]

events/urls.py
from django.conf.urls import patterns, url

from .api import (
    EventList, EventDetail,
    BetList, BetDetail,
    TransactionList, TransactionDetail
)
from .views import (
    EventDetailView, EventEmbedDetailView,
    EventFacebookObjectDetailView, EventsListView
)


api_urls = [
    url(r'^event/$', EventList.as_view(), name='event-list'),
    url(r'^event/(?P<pk>\d+)$', EventDetail.as_view(), name='event-detail'),
    url(r'^bet/$', BetList.as_view(), name='bet-list'),
    url(r'^bet/(?P<pk>\d+)$', BetDetail.as_view(), name='bet-detail'),
    url(r'^transaction/$', TransactionList.as_view(), name='transaction-list'),
    url(r'^transaction/(?P<pk>\d+)$', TransactionDetail.as_view(), name='transaction-detail'),
]

urlpatterns = patterns(
    '',
    url(r'^fbobjects/event/(?P<pk>\d+)/$', EventFacebookObjectDetailView.as_view(),
        name="event_facebook_object_detail"),
    url(r'^event/(?P<pk>\d+)-[a-zA-Z0-9\-]+$', EventDetailView.as_view(), name="event_detail"),
    url(r'^event/embed/(?P<pk>\d+)$', EventEmbedDetailView.as_view(), name='event_embed_detail'),
    url(r'^events/$', EventsListView.as_view(), {'mode': 'latest'}, name="events"),
    url(r'^events/(?P<mode>popular|last-minute|latest|changed|random|finished|draft|any)/$',
        EventsListView.as_view(),
        name="events"),
    url(r'^events/(?P<category>[\w-]+)/$', EventsListView.as_view(), name="events"),
    url(r'^bets/viewed/$', 'events.views.bets_viewed', name='bets_viewed'),
)

politikon/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns

from .api import ContactAPIView
from .views import HomeView, ContactView, acme_challenge, change_language

from events.urls import api_urls as event_api

from django.contrib import admin
admin.autodiscover()


api_urls = [
    url(r'contact/', ContactAPIView.as_view(), name='api-contact'),
    # Responsible for betting
    url(r'events/', include(event_api, namespace='api-events')),
    url(r'^auth/', include('djoser.urls.authtoken'))
]

urlpatterns = patterns(
    '',
    url(r'^change_language/(?P<lang>(pl|en|lt))$', change_language, name='change_language'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^api/', include(api_urls)),
    url(r'^.well-known/acme-challenge/(?P<acme>\w+)$', acme_challenge, name='acme_challenge'),
    url(r'^event/(?P<event_id>\d+)/transaction/create/$', 'events.views.create_transaction',
        name="create_transaction"),
    url(r'^event/(?P<event_id>\d+)/resolve/$', 'events.views.resolve_event',
        name="resolve_event"),
)

urlpatterns += i18n_patterns(
    '',
    # Admin url patterns
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    # User authentication url patternsapi
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # Application url patterns
    url(r'^', include('events.urls', namespace='events')),

    # CMS pages
    url(r'^pages/', include('cms.urls', namespace='cms')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^contact/$', ContactView.as_view(), name='contact')
)

if settings.SERVE_STATIC_FILES:
    urlpatterns += patterns(
        '',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

templates/base.html
{% load i18n path static %}

{% load modals pages %}

{% url 'accounts:rank' as rank_url %}
{% url 'events:events' as events_url %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
<link href='https://fonts.googleapis.com/css?family=Exo+2:400,400italic,500,700,300&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<title>POLITIKON - Stawiamy na politykę!</title>
<meta charset="utf-8" />
<meta name="author" content="" />
<meta name="description" content="Politikon to serwis internetowy, którego celem jest popularyzowanie pozytywnego spojrzenia na politykę, a także wyłonienia osób, które potrafią przewidywać wydarzenia społeczno-polityczne. Projekt ma pokazać, że polityka to nie tylko cyniczna, losowa gra, ale także miejsce ścierania się idei, pomysłów, miejscem gdzie przyczyny powodują określone skutki. Serwis jest grą internetową, której uczestnicy będą mogli zakładać się o wyniki różnych wydarzeń społeczno-politycznych. Giełdowy charakter gry (rynek przewidywań) pozwala pokazać prawdopodobieństwo wystąpienia określonych wydarzeń, co sprawia, że serwis jest interesującą alternatywą dla sondaży." />
<meta name="keywords" content="polityka" />

{% block facebook_properties %}
<meta property="og:title" content="POLITIKON - Stawiamy na politykę!" />
<meta property="og:description" content="Politikon to serwis internetowy, którego celem jest popularyzowanie pozytywnego spojrzenia na politykę, a także wyłonienia osób, które potrafią przewidywać wydarzenia społeczno-polityczne. Projekt ma pokazać, że polityka to nie tylko cyniczna, losowa gra, ale także miejsce ścierania się idei, pomysłów, miejscem gdzie przyczyny powodują określone skutki. Serwis jest grą internetową, której uczestnicy będą mogli zakładać się o wyniki różnych wydarzeń społeczno-politycznych. Giełdowy charakter gry (rynek przewidywań) pozwala pokazać prawdopodobieństwo wystąpienia określonych wydarzeń, co sprawia, że serwis jest interesującą alternatywą dla sondaży." />
{% endblock %}
<meta property="og:image" content="{% static 'img/logo-big.png' %}" />
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:site_name" content="Politikon" />
<meta property="fb:app_id" content="{{ facebook_app_id }}" />
{% for moderator in facebook_moderators %}
<meta property="fb:admins" content="{{ moderator }}" />
{% endfor %}

<link rel="icon" href=favicon.ico sizes="16x16 32x32 48x48 64x64" type=image/vnd.microsoft.icon>
<meta name="viewport" content="width=device-width">

<link rel="stylesheet" href="{% static 'css/style.css?v=6' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/rwd.css' %}" type="text/css" />

<!--css dla zalogowanego-->
<link rel="stylesheet" href="{% static 'css/jquery.jscrollpane.css' %}" type="text/css" />

<!-- IntroJs styles -->
<link href="{% static 'css/introjs.min.css' %}" rel="stylesheet">

<link rel="icon" type="image/png" href="{% static 'img/02reputysmall.png' %}" />

<!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>

    <link rel="stylesheet" href="{% static 'css/j24IE.css' %}" type="text/css" />
<![endif]-->

<!--[if lt IE 9]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
<![endif]-->
<!-- ^^ wsparcie dla IE pod http://code.google.com/p/ie7-static/js/ -->

{#<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>#}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/jquery.dotdotdot.min.js' %}"></script>
<!-- validation -->
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<!-- infinite scrolling -->
<script type="text/javascript" src="{% static 'js/waypoints/jquery.waypoints.min.js?v=401' %}"></script>
<script type="text/javascript" src="{% static 'js/waypoints/infinite.min.js?v=401' %}"></script>
<!--<script src="static/js/skrypty.js"></script>-->

{% if not user.is_authenticated %}
<!--WALIDACJA FORMULARZA-->
<script src="{% static 'js/walidacja/parsley.min.js' %}"></script>
{% else %}
<!--skrypty dla zalogowanego-->
<script type="text/javascript" language="javascript" src="{% static 'js/loggedin.js?v=4' %}"></script>
<!-- the mousewheel plugin -->
<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
<!-- the jScrollPane script -->
<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scroll-startstop.events.jquery.js' %}"></script>
{% endif %}
{% if user.is_staff %}
<!--skrypty dla redakcji-->
<script type="text/javascript" language="javascript" src="{% static 'js/staff.js?v=2' %}"></script>
{% endif %}


</head>


<body id="POLITIKON">
<div id="fb-root"></div>

{% choose_modal user event %}

<div id="cookie-info-container" style="display: none;">
    {% trans 'Ta strona używa cookie w celach statystycznych. Korzystając z niej wyrażasz zgodę na ich używanie, zgodnie z ustawieniami przeglądarki.' %}
&nbsp; &nbsp; <button type="button" class="close"><span aria-hidden="true">&times;</span></button>
</div>
<div id="body-wrapper">
    <section id="maintop" class="section-nopadding">
        <div class="logo lewa">
            <a href="/"><div></div></a>
        </div>
        <nav class="astable lewa">
            <div class="burger"></div>
            <ul id="mainmenu" class="mainmenu small-popup">
                <div class="arrowup"></div>
                <a href="{{ events_url }}"><li {% if request.path|startswith:events_url %} class="active"{% endif %}>{% trans "Events" %}</li></a>
                <a href="{{ rank_url }}"><li {% if request.path|startswith:rank_url %} class="active"{% endif %}>{% trans "Leaderboard" %}</li></a>
                <a href="javascript:void(0);" onclick="startIntro();" class="intro-start"><li>{% trans "Tutorial" %}</li></a>
            </ul>
        </nav>

    {% if not user.is_authenticated %}
        {% include 'not_logged_in.html' %}
    {% else %}
        {% include 'logged_in.html' %}
    {% endif %}
    {% if user.team_id %}
        <div class='anp_banner'>
            <a href="/{{ LANGUAGE_CODE }}/pages/anp"> {% trans "Akademia Nowoczesnego Patriotyzmu - Dowiedz się więcej "%} </a>
        </div>
    {% endif %}

    </section>

    {% block content %}{% endblock %}

    <section id="partners">
        <a href="http://erasmusplus.org.pl/"><div class="logo erasmus-plus"></div></a>
        <a href="http://kodujdlapolski.pl/"><div class="logo kdp"></div></a>
        <a href="http://www.kj.org.pl/"><div class="logo kj"><h5>Klub Jagielloński</h5><p>www.kj.org.pl</p></div></a>
        <div class="clr"></div>
    </section>

    <section id="erasmus-info">
      <p>Projekt finansowany ze środków Unii Europejskiej w ramach programu Erasmus+</p>
      <div class="clr"></div>
    </section>

    <footer>
        <div class="lewa">
            <ul>
                <h5>Politikon</h5>
                <li><a href="{% url 'events:events' %}">{% trans "Events" %}</a></li>
                <li><a href="{% url 'accounts:rank' %}">{% trans "Leaderboard" %}</a></li>
                <li><a href="javascript:void(0);" onclick="startIntro();">{% trans "Tutorial" %}</a></li>
                <li><a href="{% url 'contact' %}">{% trans "Contact" %}</a></li>
            </ul>
            {% published_pages %}
            <ul>
                <h5>{% trans "Partners" %}</h5>
                <li><a href="http://jagiellonski24.pl/">jagielloński24</a></li>
                <li><a href="http://anp.kj.org.pl/">{% trans "Academy of Modern Patriotism" %}</a></li>
            </ul>
        </div>
        <div class="prawa">
            <div class="socialmedia prawa">
                <a href="https://twitter.com/Politikon_KJ"><div class="tt lewa"></div></a>
                <a href="https://www.facebook.com/politikon.game/"><div class="fb lewa"></div></a>
                {#<a href="http://plus.google.com/"><div class="gp lewa"></div></a>#}
            </div>
            <nav class="languages">
              {% include 'language-bar.html' %}
            </nav>
        </div>
    </footer>
</div>

<!-- ChartJS scripts -->
<script type="text/javascript" language="javascript" src="{% static 'js/Chart.min.js' %}"></script>

<!-- Noty scripts -->
<script type="text/javascript" language="javascript" src="{% static 'js/noty/packaged/jquery.noty.packaged.min.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/noty/layouts/topRight.js' %}"></script>

<!-- IntroJS scripts -->
<script type="text/javascript" src="{% static 'js/intro/intro.min.js' %}"></script>

{% with "js/locale/"|add:LANGUAGE_CODE|add:".js?v=3" as locale_path %}
<script type="text/javascript" language="javascript" src="{% static locale_path %}"></script>
{% endwith %}

<script type="text/javascript" language="javascript" src="{% static 'js/api.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/actions.js?v=11' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/charts/betfeed_featured.js' %}"></script>

{% block js_scripts %}
{% endblock %}

{# facebook script #}
<script type="text/javascript">
window.fbAsyncInit = function () {
  FB.init({
      appId: '{{ facebook_app_id }}',
      xfbml: true,
      version: 'v2.9'
  });
};

(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

{# Google Analytics #}
<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-78893476-1', 'auto');
ga('send', 'pageview');
</script>

{# Hotjar Tracking Code for www.politikon.org.pl #}
<script type="text/javascript">
(function(h,o,t,j,a,r){
    h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
    h._hjSettings={hjid:352781,hjsv:5};
    a=o.getElementsByTagName('head')[0];
    r=o.createElement('script');r.async=1;
    r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
    a.appendChild(r);
})(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

{% if messages %}
<script type="text/javascript">
$(function () {
{% for message in messages %}
    noty({
        layout: 'topRight',
        text: '{{ message }}',
        type: '{{ message.tags }}'
    });
{% endfor %}
});
</script>
{% endif %}

</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% load i18n static %}

{% block content %}
    <section id="header" class="body-margin">
        <h3 class="orangetxt">{% trans 'Contact' %}</h3>
    </section>
    <section id="contact">
        <div id="contact-us">
            <form id="contact-form" action="/api/contact/" method="post" class="settings-form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group required">
                    <label for="name">{% trans "First name" %}</label>
                    <input name="name" class="jednalinia" type="text" required />
                </div>
                <div class="form-group required">
                    <label for="email">{% trans "Email" %}</label>
                    <input name="email" class="jednalinia" type="email" required />
                </div>
                <div class="form-group required">
                    <label for="message">{% trans "Message" %}</label>
                    <textarea name="message" class="jednalinia"></textarea>
                </div>
                <div class="form-group text-center">
                    <button id="send-message-submit"
                            class="big-button"
                            type="submit"
                            title="{% trans "Send message" %}">{% trans "Send message" %}</button>
                </div>
            </form>
        </div>
        <div id="contact-done" class="nodisplay">
            <h1>{% trans "Thank you for the message. We will reply as soon as we can." %} :)</h1>
        </div>

    </section>

    <div class="clr"></div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% load display %}
{% load format %}
{% load humanize %}
{% load i18n %}

{% load user %}

{% block facebook_properties %}
{{ block.super }}
<meta property="og:image" content="{{ front_event.small_image.url }}" />
{% for event in featured_events %}
<meta property="og:image" content="{{ event.small_image.url }}" />
{% endfor %}
{% endblock %}

{% block js_scripts %}
{% if not user.is_authenticated %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/intro/scenario-guest.js"></script>
{% else %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/intro/scenario-user.js"></script>
{% endif %}
{% endblock %}


{% block content %}
    <section id="featured" class="section-nopadding">
        <figure>
            {% if front_event.big_image %}
            <div style="background: url({{ front_event.big_image.url }}) center; height: 70vh; min-height: 200px; background-size: cover"></div>
            {% else %}
            <img src="{{ STATIC_URL }}img/featured.jpg"/>
            {% endif %}
            <figcaption>
                <a href="{{ front_event.get_relative_url }}">
                    <div class="details">
                        <div style="
                            display: block;
                            z-index: 10000;
                            position: absolute;
                            color: rgba(255,255,255,0.8);
                            top: 10px;
                            left: 10px;">
                            {% trans "Estimated closure:" %} {{ front_event.estimated_end_date|naturaltime }}
                        </div>
                        <div>
                            <canvas id="featured-canvas" height="70" data-id="{{ front_event.id }}" data-chart="{{ front_event.get_JSON_big_chart }}"></canvas>
                        </div>
                    </div>
                </a>
                <div class="opis">
                    <a href="{{ front_event.get_relative_url }}"><h1 class="skroc lewa">{{ front_event.title }}</h1></a>
                    <div id="makeabet" class="prawa collapsible{% if front_event_bet.extension.has_any %} morebets{% endif %}">
                        {% if front_event %}
                            {% render_bet front_event %}
                        {% endif %}
                    </div>
                </div>
            </figcaption>
        </figure>
    </section>

    <section id="betfeed" class="padding-bottom">
        {% render_events featured_events %}
    </section>

    <section id="betfeed" class="hotbets">
        <h3 class="orangeheader goupheader">{% trans "Ending" %} <div class="prawa hotbet-icon"></div></h3>
        <div>
            {% render_events last_minute_events %}
        </div>
    </section>

    <section id="ranking-short">
        <h3 class="orangetxt lewa">{% trans "Best players" %}</h3>
        <ul class="tabs prawa">
            <li class="active"><a href="#tydzien">{% trans "weekly" %}</a></li>
            <li><a href="#miesiac">{% trans "monthly" %}</a></li>
            <li><a href="#calosc">{% trans "overall" %}</a></li>
        </ul>
        <div class="clr"></div>
        <div id="userrank_content" class="zakladki-content">
            <article id="tydzien" class="active">
                {% for user in best_weekly %}
                {% user_home user user.weekly_result True %}
                {% endfor %}
            </article>
            <article id="miesiac">
                {% for user in best_monthly %}
                {% user_home user user.monthly_result True %}
                {% endfor %}
            </article>
            <article id="calosc">
                {% for user in best_overall %}
                {% user_home user user.reputation %}
                {% endfor %}
            </article>
        </div>
    </section>

{#    <section id="loadmore">#}
{#        <a href="{% url 'events:events' %}"><div class="btn astable">{% trans "Show more events" %}</div></a>#}
{#        <div class="more lewa"></div>#}
{#        <div class="more prawa"></div>#}
{#        <div class="more centrum"></div>#}
{#    </section>#}


{% endblock %}

templates/logged_in.html
{% load display %}
{% load format %}
{% load i18n %}

<div class="fixed-vertical-left-btn-div">
    <a href="#" class="side-helper" id="add-event-button">{% trans "Suggest an event" %}</a>
</div>

<div class="graj avatar prawa">
    <div class="image" style="background-image: url({{ user.get_avatar_url }});"></div>
    <nav class="avatarmenu">
        <ul id="avatarmenu">
            <li><a href="{% url 'accounts:user_profile' %}">{% trans "My profile" %}</a></li>
            <li><a href="{% url 'accounts:user_settings' %}">{% trans "Settings" %}</a></li>
            <li><a href="{% url 'accounts:logout' %}">{% trans "Log out" %}</a></li>
        </ul>
    </nav>
</div>

<div class="userdata prawa">
    {# <!--klasa .notification dodawana przy powiadomieniach (wtedy,gdy klasa .wallet zawiera span)--> #}
    <a href="{% if user.get_newest_results.count %}#{% else %}{% url 'accounts:user_profile' %}#zawartoscportfela{% endif %}">
        <div class="lewa wallet{% if user.get_newest_results.count %} notification{% endif %}">
            {% if user.get_newest_results.count %}
                <span id="wallet_notification_count">{{ user.get_newest_results.count }}</span>
            <div id="arrowup" class="arrowup small-popup"></div>
        {% endif %}
        </div>
    </a>

    <a href="{% url 'accounts:user_profile' %}">
        <div class="lewa stats">
            <p>{% trans "portfolio value" %}</p>
            <p class="walletvalue">{{ user.portfolio_value|formatted }}</p>
        </div>
    </a>

    <a href="{% url 'accounts:user_profile' %}">
        <div class="lewa stats">
            <p>{% trans "points to use" %}</p>
            <p class="freevalue">{{ user.total_cash|formatted }}</p>
        </div>
    </a>

    <a href="{% url 'accounts:user_profile' %}">
        <div class="lewa stats">
            <p>{% trans "performance" %}</p>
            <p class="reputationvalue">{{ user.reputation|formatted }}%</p>
        </div>
    </a>
</div>

<section id="wallet-not" class="centrum small-popup">
    <div class="container">
        <div class="inside">
            <div class="header">
                {% trans "fresh outcomes" %}
                <a id="all-bets-result" href="#"><span>{% trans "Mark as read" %}</span></a>
            </div>
            <div id="jp-container" class="jp-container">
            {% for bet in user.get_newest_results %}
                <a class="a-betresult" data-bet_id="{{ bet.id }}" href="{{ bet.event.get_relative_url }}">
                    <div class="betresult new">
                    {% if bet.event.small_image %}
                        <div class="image" style="background-image: url({{ bet.event.small_image.url }});"></div>
                    {% else %}
                        <div class="image" style="background-image: url({{ STATIC_URL }}img/bet-plain.jpg);"></div>
                    {% endif %}
                        {% render_bet_status bet %}
                        <div class="status-change">
                            {% trans "profit" %}/{% trans "loss" %}:
                            <div class="{% if bet.is_won %}changeYES{% else %}changeNO{% endif %}">{{ bet.get_wallet_change|formatted:"True" }}</div>
                            <p><span class="invested">{{ bet.get_invested|formatted }}</span> <span class="won">{{ bet.get_won|formatted }}</span></p>
                        </div>
                    </div>
                </a>
            {% endfor %}
            </div>
            <a href="{% url 'accounts:user_profile' %}#powiadomieniaowynikach" id="go-to-all-results"><div class="viewall">{% trans "Show all results" %}</div></a>
        </div>
    </div>
</section>

templates/macros.html
{% macro pubnub_init() %}
      var pubnub = PUBNUB.init({
        subscribe_key: "{{ settings.PUBNUB_SUBSCRIBE_KEY }}"
    });
{% endmacro %}

{% macro TODO_remove_it_render_event(event, people) %}
  <a class="no-decoration" href="{% url 'events:event_detail' event_id=event.id %}?{{ request.canvas_query }}">
    <div class="event">
      {% if event.small_image %}
        <img src="{{ event.small_image.url }}" width={{ config.SMALL_EVENT_IMAGE_WIDTH }} height={{ config.SMALL_EVENT_IMAGE_HEIGHT }} />         
      {% endif %}
      <div class="valign-middle-wrapper">
        <div class="valign-middle">
        <h5 class="title">{{ event.title }}</h3>
          </div>
      </div>
      <p class="short-title">{{ event.short_title }}</p>

      <div class="stats stats-yes">
        <table>
          <tr>
            <td class="outcome">{% trans %}YES{% endtrans %}</td>
            <td class="price">{{ event.current_buy_for_price }} <span class="trend">(+0.0%)</span></td>
            <td class="friends">
              {% for friend in people[event.id]['YES'] %}
                {% if friend.profile_photo %}
                  <img src="{{ friend.profile_photo }}" width=50 height=50 />
                {% endif %}
              {% endfor %}
            </td>
          </tr>
        </table>
      </div>
      <div class="stats stats-no">
        <table>
          <tr>
            <td class="outcome">{% trans %}NO{% endtrans %}</td>
            <td class="price">{{ event.current_buy_against_price }} <span class="trend">(+0.0%)</span></td>
            <td class="friends">
              {% for friend in people[event.id]['NO'] %}
                {% if friend.profile_photo %}
                  <img src="{{ friend.profile_photo }}" width=50 height=50 />
                {% endif %}
              {% endfor %}
            </td>
          </tr>
        </table>
      </div>

    </div>
  </a>
{% endmacro %}

templates/not_logged_in.html
{% load i18n %}

<div class="graj prawa">
    <a href="#"><div class="prawa show-login">{% trans "PLAY" %}!</div></a>
</div>

<nav class="prawa languages">
  {% include 'language-bar.html' %}
</nav>